config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  
  get '/home', to: 'pages#home'
  
  resources :reports
  
end

app/models/report.rb
class Report < ActiveRecord::Base
    validates :email, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.email = email.downcase }
    validates :username, presence: true
    VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
   
   def home
   end
    
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
   
   def index
       @reports = Report.all
   end
   
   
   def create
       @report = Report.new(recipe_params)
       if @report.save
         @bandera = 1
         UserMailer.notification_email(@report).deliver_now
         render :success
       else
         @bandera = 0
         render :new
       end
   end
   
   
   def new
       @bandera = 0
       @report = Report.new
   end
   
   
   def edit
   
   end
   
   
   def show
       @report = Report.find(params[:id])
   end
   
   
   def update
       
   end
   
   
   def destroy
       
   end
   
   def success
      if @bandera = 1
         @report = Report.find(params[:id])
      else
         render :new
      end
   end
    
   private
      def recipe_params
         params.require(:report).permit(:calle, :colonia, :municipio, :cp, :hechos, :referencias, :email, :coords)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/notification_denuncia.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8"> <!-- utf-8 works for most cases -->
    <meta name="viewport" content="width=device-width"> <!-- Forcing initial-scale shouldn't be necessary -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge"> <!-- Use the latest (edge) version of IE rendering engine -->
    <meta name=”x-apple-disable-message-reformatting”>  <!-- Disable auto-scale in iOS 10 Mail entirely -->
    <title></title> <!-- The title tag shows in email notifications, like Android 4.4. -->

    <!-- Web Font / @font-face : BEGIN -->
    <!-- NOTE: If web fonts are not required, lines 9 - 26 can be safely removed. -->
    
    <!-- Desktop Outlook chokes on web font references and defaults to Times New Roman, so we force a safe fallback font. -->
    <!--[if mso]>
        <style>
            * {
                font-family: sans-serif !important;
            }
        </style>
    <![endif]-->
    
    <!-- All other clients get the webfont reference; some will render the font and others will silently fail to the fallbacks. More on that here: http://stylecampaign.com/blog/2015/02/webfont-support-in-email/ -->
    <!--[if !mso]><!-->
        <!-- insert web font reference, eg: <link href='https://fonts.googleapis.com/css?family=Roboto:400,700' rel='stylesheet' type='text/css'> -->
    <!--<![endif]-->

    <!-- Web Font / @font-face : END -->
    
      <!-- CSS Reset -->
    <style>

        /* What it does: Remove spaces around the email design added by some email clients. */
        /* Beware: It can remove the padding / margin and add a background color to the compose a reply window. */
        html,
        body {
            margin: 0 auto !important;
            padding: 0 !important;
            height: 100% !important;
            width: 100% !important;
        }
        
        /* What it does: Stops email clients resizing small text. */
        * {
            -ms-text-size-adjust: 100%;
            -webkit-text-size-adjust: 100%;
        }
        
        /* What is does: Centers email on Android 4.4 */
        div[style*="margin: 16px 0"] {
            margin:0 !important;
        }
        
        /* What it does: Stops Outlook from adding extra spacing to tables. */
        table,
        td {
            mso-table-lspace: 0pt !important;
            mso-table-rspace: 0pt !important;
        }
                
        /* What it does: Fixes webkit padding issue. Fix for Yahoo mail table alignment bug. Applies table-layout to the first 2 tables then removes for anything nested deeper. */
        table {
            border-spacing: 0 !important;
            border-collapse: collapse !important;
            table-layout: fixed !important;
            margin: 0 auto !important;
        }
        table table table {
            table-layout: auto; 
        }
        
        /* What it does: Uses a better rendering method when resizing images in IE. */
        img {
            -ms-interpolation-mode:bicubic;
        }
        
        /* What it does: A work-around for iOS meddling in triggered links. */
        .mobile-link--footer a,
        a[x-apple-data-detectors] {
            color:inherit !important;
            text-decoration: underline !important;
        }
      
    </style>
    
    <!-- Progressive Enhancements -->
    <style>
        
        /* What it does: Hover styles for buttons */
        .button-td,
        .button-a {
            transition: all 100ms ease-in;
        }
        .button-td:hover,
        .button-a:hover {
            background: #555555 !important;
            border-color: #555555 !important;
        }

    </style>

</head>
<body width="100%" bgcolor="#222222" style="margin: 0;">
    <center style="width: 100%; background: #eaeaea;">

        <!--    
            Set the email width. Defined in two places:
            1. max-width for all clients except Desktop Windows Outlook, allowing the email to squish on narrow but never go wider than 600px.
            2. MSO tags for Desktop Windows Outlook enforce a 600px width.
        -->
        <div style="max-width: 600px; margin: auto;">
            <!--[if mso]>
            <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="600" align="center">
            <tr>
            <td>
            <![endif]-->

            <!-- Email Header : BEGIN -->
            <table role="presentation" cellspacing="0" cellpadding="0" border="0" align="center" width="100%" style="max-width: 600px;">
                <!--
                <tr>
                    <td style="padding: 20px 0; text-align: center">
                        <img src="http://www.webshau.com/images/logo-nav.png" width="200" height="auto" alt="alt_text" border="0" style="font-family: sans-serif; font-size: 15px; mso-height-rule: exactly; line-height: 20px; color: #555555;">
                    </td>
                </tr> -->
            </table>
            <!-- Email Header : END -->
            
            <!-- Email Body : BEGIN -->
            <table role="presentation" cellspacing="0" cellpadding="0" border="0" align="center" width="100%" style="max-width: 600px;">
                
                <!-- Hero Image, Flush : BEGIN -->
                <tr>
                    <td bgcolor="#ffffff">
                        <img src="http://www.webshau.com/images/background_email.jpg" width="600" height="" alt="alt_text" border="0" align="center" style="width: 100%; max-width: 600px; background: #dddddd; font-family: sans-serif; font-size: 15px; mso-height-rule: exactly; line-height: 20px; color: #555555;">
                    </td>
                </tr>
                <!-- Hero Image, Flush : END -->

                <!-- 1 Column Text + Button : BEGIN -->
                <tr>
                    <td bgcolor="#ffffff">
                        <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%">
                            <tr>
                                <td style="padding: 40px; font-family: sans-serif; font-size: 15px; mso-height-rule: exactly; line-height: 20px; color: #555555;">
                                    <font style="font-size: 18px; font-weight: 700; color: #028090; text-align: center;">¡Nueva Denuncia!<br><br></font>
                                    
                                    <font style="font-weight: 400; color: #028090;">Dirección: <strong><%= @report.calle %></strong></font><br><br>
        
        Colonia: <%= @report.colonia %>
        <br><br>
        Hechos: <%= @report.hechos %>
        <br><br>
        Correo: <%= @report.email %>
                                        
                                    <br><br>
                                        
                                        <font style="font-size:16px; color: #621668"><strong>Denuncia An&oacute;nima</strong></font>
                                </td>
                                </tr>
                        </table>
                    </td>
                </tr>
            </table>
            <!-- Email Body : END -->
          
            <!-- Email Footer : BEGIN -->
            <table role="presentation" cellspacing="0" cellpadding="0" border="0" align="center" width="100%" style="max-width: 680px;">
                <tr>
                    <td style="padding: 40px 10px;width: 100%;font-size: 12px; font-family: sans-serif; mso-height-rule: exactly; line-height:18px; text-align: center; color: #888888;">
                        <br><br>
                        Secretaría de Protección al Medio Ambiente
                        <br><br>
                    </td>
                </tr>
            </table>
            <!-- Email Footer : END -->

            <!--[if mso]>
            </td>
            </tr>
            </table>
            <![endif]-->
        </div>
    </center>
</body>
</html>

app/views/layouts/notification_email.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8"> <!-- utf-8 works for most cases -->
    <meta name="viewport" content="width=device-width"> <!-- Forcing initial-scale shouldn't be necessary -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge"> <!-- Use the latest (edge) version of IE rendering engine -->
    <meta name=”x-apple-disable-message-reformatting”>  <!-- Disable auto-scale in iOS 10 Mail entirely -->
    <title></title> <!-- The title tag shows in email notifications, like Android 4.4. -->

    <!-- Web Font / @font-face : BEGIN -->
    <!-- NOTE: If web fonts are not required, lines 9 - 26 can be safely removed. -->
    
    <!-- Desktop Outlook chokes on web font references and defaults to Times New Roman, so we force a safe fallback font. -->
    <!--[if mso]>
        <style>
            * {
                font-family: sans-serif !important;
            }
        </style>
    <![endif]-->
    
    <!-- All other clients get the webfont reference; some will render the font and others will silently fail to the fallbacks. More on that here: http://stylecampaign.com/blog/2015/02/webfont-support-in-email/ -->
    <!--[if !mso]><!-->
        <!-- insert web font reference, eg: <link href='https://fonts.googleapis.com/css?family=Roboto:400,700' rel='stylesheet' type='text/css'> -->
    <!--<![endif]-->

    <!-- Web Font / @font-face : END -->
    
      <!-- CSS Reset -->
    <style>

        /* What it does: Remove spaces around the email design added by some email clients. */
        /* Beware: It can remove the padding / margin and add a background color to the compose a reply window. */
        html,
        body {
            margin: 0 auto !important;
            padding: 0 !important;
            height: 100% !important;
            width: 100% !important;
        }
        
        /* What it does: Stops email clients resizing small text. */
        * {
            -ms-text-size-adjust: 100%;
            -webkit-text-size-adjust: 100%;
        }
        
        /* What is does: Centers email on Android 4.4 */
        div[style*="margin: 16px 0"] {
            margin:0 !important;
        }
        
        /* What it does: Stops Outlook from adding extra spacing to tables. */
        table,
        td {
            mso-table-lspace: 0pt !important;
            mso-table-rspace: 0pt !important;
        }
                
        /* What it does: Fixes webkit padding issue. Fix for Yahoo mail table alignment bug. Applies table-layout to the first 2 tables then removes for anything nested deeper. */
        table {
            border-spacing: 0 !important;
            border-collapse: collapse !important;
            table-layout: fixed !important;
            margin: 0 auto !important;
        }
        table table table {
            table-layout: auto; 
        }
        
        /* What it does: Uses a better rendering method when resizing images in IE. */
        img {
            -ms-interpolation-mode:bicubic;
        }
        
        /* What it does: A work-around for iOS meddling in triggered links. */
        .mobile-link--footer a,
        a[x-apple-data-detectors] {
            color:inherit !important;
            text-decoration: underline !important;
        }
      
    </style>
    
    <!-- Progressive Enhancements -->
    <style>
        
        /* What it does: Hover styles for buttons */
        .button-td,
        .button-a {
            transition: all 100ms ease-in;
        }
        .button-td:hover,
        .button-a:hover {
            background: #555555 !important;
            border-color: #555555 !important;
        }

    </style>

</head>
<body width="100%" bgcolor="#222222" style="margin: 0;">
    <center style="width: 100%; background: #eaeaea;">

        <!--    
            Set the email width. Defined in two places:
            1. max-width for all clients except Desktop Windows Outlook, allowing the email to squish on narrow but never go wider than 600px.
            2. MSO tags for Desktop Windows Outlook enforce a 600px width.
        -->
        <div style="max-width: 600px; margin: auto;">
            <!--[if mso]>
            <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="600" align="center">
            <tr>
            <td>
            <![endif]-->

            <!-- Email Header : BEGIN -->
            <table role="presentation" cellspacing="0" cellpadding="0" border="0" align="center" width="100%" style="max-width: 600px;">
                <!--
                <tr>
                    <td style="padding: 20px 0; text-align: center">
                        <img src="http://www.webshau.com/images/logo-nav.png" width="200" height="auto" alt="alt_text" border="0" style="font-family: sans-serif; font-size: 15px; mso-height-rule: exactly; line-height: 20px; color: #555555;">
                    </td>
                </tr> -->
            </table>
            <!-- Email Header : END -->
            
            <!-- Email Body : BEGIN -->
            <table role="presentation" cellspacing="0" cellpadding="0" border="0" align="center" width="100%" style="max-width: 600px;">
                
                <!-- Hero Image, Flush : BEGIN -->
                <tr>
                    <td bgcolor="#ffffff">
                        <img src="http://www.webshau.com/images/background_email.jpg" width="600" height="" alt="alt_text" border="0" align="center" style="width: 100%; max-width: 600px; background: #dddddd; font-family: sans-serif; font-size: 15px; mso-height-rule: exactly; line-height: 20px; color: #555555;">
                    </td>
                </tr>
                <!-- Hero Image, Flush : END -->

                <!-- 1 Column Text + Button : BEGIN -->
                <tr>
                    <td bgcolor="#ffffff">
                        <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%">
                            <tr>
                                <td style="padding: 40px; font-family: sans-serif; font-size: 15px; mso-height-rule: exactly; line-height: 20px; color: #555555;">
                                    <font style="font-size: 18px; font-weight: 700; color: #028090; text-align: center;">¡Nueva Denuncia!<br><br></font>
                                    
                                    <font style="font-weight: 400; color: #028090;">Dirección: <strong><%= @report.calle %></strong></font><br><br>
        
        Colonia: <%= @report.colonia %>
        <br><br>
        Hechos: <%= @report.hechos %>
        <br><br>
        Correo: <%= @report.email %>
                                        
                                    <br><br>
                                        
                                        <font style="font-size:16px; color: #621668"><strong>Denuncia An&oacute;nima</strong></font>
                                </td>
                                </tr>
                        </table>
                    </td>
                </tr>
            </table>
            <!-- Email Body : END -->
          
            <!-- Email Footer : BEGIN -->
            <table role="presentation" cellspacing="0" cellpadding="0" border="0" align="center" width="100%" style="max-width: 680px;">
                <tr>
                    <td style="padding: 40px 10px;width: 100%;font-size: 12px; font-family: sans-serif; mso-height-rule: exactly; line-height:18px; text-align: center; color: #888888;">
                        <br><br>
                        Secretaría de Protección al Medio Ambiente
                        <br><br>
                    </td>
                </tr>
            </table>
            <!-- Email Footer : END -->

            <!--[if mso]>
            </td>
            </tr>
            </table>
            <![endif]-->
        </div>
    </center>
</body>
</html>

app/views/layouts/notification_email.text.erb
Nueva denuncia! 
---------------------------------------------

Calle: <%= @report.calle %>

Correo: <%= @report.email %>

Telefono: <%= @report.hechos %>

app/views/pages/home.html.erb
<div class="container portada-container">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1 col-md-8 col-md-offset-2">
            <%= image_tag("logo.png", class: "logo-center") %>
            <h3 class="text-center">Bienvenido al Sistema de Denuncia An&oacute;nima Ambiental</h3>
            <p class="text-center">Tu denuncia es totalmente an&oacute;nima, en ning&uacute;n momento te solicitaremos tu nombre o domicilio. Para generar una denuncia d&aacute; clic en el bot&oacute;n y sigue las instrucciones. Es necesario que permitas detectar tu ubicación para una denuncia precisa.</p>
        </div>
        <div class="col-xs-10 col-xs-offset-1 col-md-8 col-md-offset-2">
            <a href="/reports/new" class="next-btn">Crear denuncia</a>
        </div>
    </div>
</div>

<a href="http://www.spabc.gob.mx/" class="volver-a-sitio"><%= image_tag("left-arrow.svg") %> VOLVER A SITIO PRINCIPAL</a>

app/views/reports/index.html.erb
<div class="logo-nav"><!-- NAVBAR -->
    <a href="/reports"><%= image_tag("logo.png") %></a>    
</div>

<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <h2 class="text-center">Denuncias</h2>
        </div>
    </div>
    <div class="row">
        <div class="section col-xs-12">
            <div class="col-md-2">
                <strong>Folio</strong>
            </div>
            <div class="col-md-5">
                <strong>Direcci&oacute;n</strong>
            </div>
            <div class="col-md-3">
                <strong>Ciudad</strong>
            </div>
            <div class="col-md-2">
                <strong>Fecha</strong>
            </div>
        </div>
        <% @reports.order("created_at desc").each do |report| %>
        <div class="section col-xs-12">
            <div class="col-md-2">
                <%= link_to report.id+1500, report_path(report) %>
            </div>
            <div class="col-md-5">
                <%= link_to report.calle, report_path(report) %>
            </div>
            <div class="col-md-3">
                <%= report.municipio %>
            </div>
            <div class="col-md-2">
                <%= link_to report.created_at.strftime("%Y-%m-%d"), report_path(report) %>
            </div>
        </div>
        <% end %>
        
    </div>
</div>

app/views/reports/new.html.erb
<!-- UBICACION VIEW MAPA -->
<div class="container" id="ubicacion-mapa-view">
    <div class="row">
        <div class="col-xs-12 col-xs-offset-0 col-md-8 col-md-offset-2">
            <%= image_tag("location.svg", class: "location-icon") %>
            <h3 class="text-center">Ubicaci&oacute;n de fuente contaminante</h3>
            <p class="text-center">Es necesario que permitas el uso de tu ubicaci&oacute;n en tu navegador.
            <br>
            Corrige tu ubicaci&oacute;n posicionando el marcador.
            </p>
        </div>
        
        <div class="col-xs-12 mapa-ubicacion">
            <div id="map"></div>
            
            <p>Coord: <span id="clat"><!-- COORDENADA --></span></p>
        </div>
        
        <div class="col-xs-12 section">
            <h3>Direcci&oacute;n de fuente contaminante</h3>
            <%= form_for @report do |f| %>
                
                <div class="col-xs-12 col-md-6">
                <%= f.label :calle, class: "form-label" %>
                <%= f.text_field :calle, id: "calle", class: "form-input" %>
                </div>
                
                <div class="col-xs-12 col-md-6">
                <%= f.label :colonia, class: "form-label" %>
                <%= f.text_field :colonia, id: "colonia", class: "form-input" %>
                </div>
                
                <div class="col-xs-12 col-md-6">
                <%= f.label :municipio, class: "form-label" %>
                <%= f.text_field :municipio, id: "ciudad", class: "form-input" %>
                </div>
                
                <div class="col-xs-12 col-md-6">
                <%= f.label :cp, class: "form-label" %>
                <%= f.text_field :cp, id: "cp", class: "form-input" %>
                </div>
                
                <div class="hidden-xs hidden-sm hidden-md hidden-lg">
                <%= f.text_field :coords, id: "coords", class: "form-input" %>    
                </div>
                
        </div>
        
        <div class="col-xs-12 section">
                
                <h3>Declaraci&oacute;n</h3>
                
                <%= f.label :hechos, class: "form-label" %>
                <%= f.text_area :hechos, class: "form-area" %>
                
                <%= f.label :referencias, class: "form-label" %>
                <%= f.text_area :referencias, class: "form-area" %>
                
        </div>
        
        <div class="col-xs-12 section">
            
                <h3>Seguimiento</h3>
                <p>Para poder actualizarte en el estado de tu denuncia o si requerimos m&aacute;s informaci&oacute;n proporcionanos un correo electr&oacute;nico de contacto, este no es obligatorio pero puede ser de ayuda.</p>
                
                <%= f.label :email, class: "form-label" %>
                <%= f.email_field :email, class: "form-input" %>
        </div>
        
        <div class="col-xs-12">
                <%= f.submit 'Crear denuncia', class: "next-btn last-btn" %>
            <% end %>
        </div>
    </div>
</div>


<a href="http://www.spabc.gob.mx/" class="volver-a-sitio"><%= image_tag("left-arrow.svg") %> VOLVER A SITIO PRINCIPAL</a>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAat7CnUNLT4-2Sp76qKGJHUWuqLWXiAl8&libraries=geometry&callback=initMap" async defer></script>

app/views/reports/show.html.erb
<div class="logo-nav"><!-- NAVBAR -->
    <a href="/reports"><%= image_tag("logo.png") %></a>    
</div>

<div class="container">
    <div class="row">
        <div class="col-xs-12">
            Folio: <%= @report.id+1500 %>
            <br>
            Calle: <%= @report.calle %>
            <br>
            Colonia: <%= @report.colonia %>
            <br>
            Ciudad: <%= @report.municipio %>
            <br>
            C.P.: <%= @report.cp %>
            <br>
            Coordenas: <%= @report.coords %>
            <br>
            Hechos: <%= @report.hechos %>
            <br>
            Referencias: <%= @report.referencias %>
            <br>
            Denuncia creada: <%= @report.created_at.strftime("%Y-%m-%d") %>
        </div>
    </div>
</div>

<a href="/reports" class="volver-a-sitio"><%= image_tag("left-arrow.svg") %> VOLVER A DENUNCIAS</a>

app/views/reports/success.html.erb
<div class="container portada-container">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1 col-md-8 col-md-offset-2">
            <%= image_tag("logo.png", class: "logo-center") %>
            <h3 class="text-center">¡Tu denuncia se ha enviado! Tu folio es: <%= @report.id+1500 %></h3>
            <p class="text-center">Se ha enviado tu denuncia al departamento correspondiente y le estaremos dando seguimiento, si ingresaste tu correo electr&oacute;nico ser&aacute;s notificado del estatus de tu denuncia.</p>
        </div>
        <div class="col-xs-10 col-xs-offset-1 col-md-8 col-md-offset-2">
            <a href="/reports/new" class="next-btn">Nueva denuncia</a>
        </div>
    </div>
</div>

<a href="http://www.spabc.gob.mx/" class="volver-a-sitio"><%= image_tag("left-arrow.svg") %> VOLVER A SITIO PRINCIPAL</a>